### PR TITLE
Bump Go to 1.19

### PR DESCRIPTION
**Pull request by lucacome**
Bumps Go to `1.19`

### CODE REVIEW

**Comment by dashpole** [comment]
We usually test against one go release behind the latest.  Would 1.18 work for your purposes?

**Comment by dashpole** [comment]
```
gofmt FAILED => gofmt the following files:

./stackdriver.go
./stats.go
./trace.go
```

**Comment by lucacome** [comment]
> We usually test against one go release behind the latest. Would 1.18 work for your purposes?

Go 1.20 is expected to be released in February 2023 😅

**Pull request closed without merging**
