### PR TITLE
Bump cloud.google.com/go dependencies

### PR DESCRIPTION
**Pull request by lucacome**
Updates cloud.google.com/go dependencies to the latest version. This causes all the other golang/google dependencies to be bumped too.

This also fixes a few CVEs in `golang.org/x/net`, `golang.org/x/sys` and `golang.org/x/text`.

### CODE REVIEW

**Comment by lucacome** [comment]
Unfortunately I can't see why the check is failing

**Comment by dashpole** [comment]
staticcheck ./...
panic: interface conversion: types.Type is nil, not *types.Signature

goroutine 14617 [running]:
honnef.co/go/tools/ir.(*builder).expr0(0xc0016a18f0, 0xc0046558c0, {0x910c68, 0xc0083578e0}, {0x0, {0x0, 0x0}, {0x0, 0x0}})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:640 +0x22fb
honnef.co/go/tools/ir.(*builder).expr(0x7fc900, 0xc0046558c0, {0x910c68, 0xc0083578e0})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:500 +0x1db
honnef.co/go/tools/ir.(*builder).expr0(0xc0016a18f0, 0xc0046558c0, {0x910ed8, 0xc0017e49d8}, {0x2, {0x90f730, 0xc0035c97a0}, {0x0, 0x0}})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:658 +0x1dc5
honnef.co/go/tools/ir.(*builder).expr(0x7fc900, 0xc0046558c0, {0x910ed8, 0xc0017e49d8})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:500 +0x1db
honnef.co/go/tools/ir.(*builder).setCallFunc(0x90, 0xc0046558c0, 0xc00722ba80, 0xc0000a45e8)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:837 +0x2ec
honnef.co/go/tools/ir.(*builder).setCall(0x7fdc80, 0xc0046558c0, 0xc00722ba80, 0xc0000a45e8)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:917 +0x31
honnef.co/go/tools/ir.(*builder).expr0(0xc0016a18f0, 0xc0046558c0, {0x910968, 0xc00722ba80}, {0x7, {0x90f758, 0xc001a75200}, {0x0, 0x0}})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:557 +0x21e6
honnef.co/go/tools/ir.(*builder).expr(0x7fdc80, 0xc0046558c0, {0x910968, 0xc00722ba80})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:500 +0x1db
honnef.co/go/tools/ir.(*builder).expr0(0xc0016a18f0, 0xc0046558c0, {0x910968, 0xc00722bac0}, {0x7, {0x90f618, 0xb84dc0}, {0x0, 0x0}})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:543 +0xa45
honnef.co/go/tools/ir.(*builder).expr(0x90ecb8, 0xc0046558c0, {0x910968, 0xc00722bac0})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:500 +0x1db
honnef.co/go/tools/ir.(*builder).stmt(0xc0017c4480, 0xc0046558c0, {0x910e78, 0xc008357960})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2138 +0x1f4e
honnef.co/go/tools/ir.(*builder).stmtList(0x10, 0x203001, {0xc0042c0a80, 0x5, 0x8})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:748 +0x67
honnef.co/go/tools/ir.(*builder).stmt(0xc0046558c0, 0xc0046558c0, {0x910908, 0xc003e25aa0})
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2185 +0x15a5
honnef.co/go/tools/ir.(*builder).buildFunction(0xc0016a18f0, 0xc0046558c0)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2296 +0x577
honnef.co/go/tools/ir.(*builder).buildFuncDecl(0x0, 0xc004324750, 0xc003e25ad0)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2334 +0x195
honnef.co/go/tools/ir.(*Package).build(0xc004324750)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2440 +0xcf2
sync.(*Once).doSlow(0xc003396fc0, 0xc00b60bb30)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
honnef.co/go/tools/ir.(*Package).Build(...)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/ir/builder.go:2358
honnef.co/go/tools/internal/passes/buildir.run(0xc002e5eb40)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/internal/passes/buildir/buildir.go:89 +0x368
honnef.co/go/tools/lint.(*Runner).runAnalysisUser(0xc000152d40, 0xc002e5eb40, 0xc00358e730)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/lint/runner.go:494 +0x24d
honnef.co/go/tools/lint.(*Runner).runAnalysis(0xc000152d40, 0xc00358e730)
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/lint/runner.go:374 +0x5fc
honnef.co/go/tools/lint.(*Runner).processPkg.func3()
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/lint/runner.go:913 +0xa5
created by honnef.co/go/tools/lint.(*Runner).processPkg
	/go/pkg/mod/honnef.co/go/tools@v0.0.1-2020.1.4/lint/runner.go:908 +0x637
make: *** [Makefile:117: staticcheck] Error 2

**Comment by lucacome** [comment]
Interesting, that's not failing for me locally

**Comment by lucacome** [comment]
I haven't fixed the deprecated warnings for `ioutil` that are in #309 I'll rebase after that one is merged.

**Comment by lucacome** [comment]
is it still the same error?

**Comment by dashpole** [comment]
yep, still the same

**Comment by lucacome** [comment]
All checks passed 🚀

**Review by dashpole — APPROVED** [review]

**Pull request merged**
