### PR TITLE
Remove the check for unique project ID within the process

### PR DESCRIPTION
**Pull request by ramonza**
Fixes: #8

### CODE REVIEW

**Comment by ramonza** [comment]
@rakyll do you recall the original reason we added this? It is making it difficult to use the exporter in Istio where it can dynamically be created and closed at runtime.

**Comment by ramonza** [comment]
ping @rakyll

**Comment by rakyll** [comment]
Stackdriver Monitoring API have issues when uploading if two or more exporters happen to upload at the same time.

**Comment by ramonza** [comment]
I believe the documentation in #20 about labels and monitored resources identifying a unique time series captures the issue sufficiently.

**Pull request merged**
